- name: Copy file with owner and permissions
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: Extract Artifact
  shell: | 
    tar -xf artifact.tar.gz

- name: Install dependencies & start PM2 
  shell: |
    cd ~/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start
